version: '0.0.2dev'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: balancer
    ports:
      - "6969:6969"
    networks:
      working:
        ipv4_address: 172.20.0.2
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert.pem:/etc/ssl/cert.pem
      - ./priv.key:/etc/ssl/priv.key

  redis_db:
    image: redis:7.0.7-alpine
    restart: always
    container_name: redis_db
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    networks:
      working:
        ipv4_address: 172.20.0.3
    volumes:
      - cache:/data

  # API

  auth:
    build: ./auth
    container_name: auth_api
    networks:
      working:
        ipv4_address: 172.20.0.4
    depends_on:
      - redis_db
    env_file:
      - api.production.env

  users:
    build: ./users
    container_name: users_api
    networks:
      working:
        ipv4_address: 172.20.0.5
    depends_on:
      - redis_db
    env_file:
      - api.production.env

networks:
  working:
    driver: external
    name: appnet # This change from devnet to appnet

volumes:
  cache:
    driver: local