version: '0.0.2dev'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: balancer
    ports:
      - "6969:6969"
    networks:
      working:
        ipv4_address: 172.20.0.2
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert.pem:/etc/ssl/cert.pem
      - ./priv.key:/etc/ssl/priv.key

  redis_db:
    image: redis:7.0.7-alpine
    restart: always
    container_name: redis_db
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    networks:
      working:
        ipv4_address: 172.20.0.3
    volumes:
      - cache:/data

  # API

  auth:
    build: ../api-auth
    container_name: auth_api
    networks:
      working:
        ipv4_address: 172.20.0.4
    depends_on:
      - redis_db
    env_file:
      - api.dev.env
    volumes:
      - ssl:/etc/ssl
    ports:
      - "5001:8080"

  users:
    build: ../api-users
    container_name: users_api
    networks:
      working:
        ipv4_address: 172.20.0.5
    depends_on:
      - redis_db
    env_file:
      - api.dev.env
    volumes:
      - ssl:/etc/ssl
    ports:
      - "5002:8080"

  #messages:
   # image: ./messages
    #container_name: messages_api
    #networks:
     # - working
    #depends_on:
     # - redis_db
    #env_file:
     # - api.production.env

  #groups:
   # image: ./groups
    #container_name: groups_api
    #networks:
     # - working
    #depends_on:
     # - redis_db
    #env_file:
     # - api.production.env

  #notifications:
   # image: ./notifications
    #container_name: notifications_api
    #networks:
    #  - working
    #depends_on:
    #  - redis_db
    #env_file:
    #  - api.production.env

  #websocket:
    #image: ./websocket
    #container_name: websocket_gateway
    #networks:
    #  - working
    #depends_on:
    #  - redis_db
    #env_file:
    #  - api.production.env

  # Databas


networks:
  working:
    driver: external
    name: devnet
#    ipam:
#      config:
#        - subnet: 172.20.0.0/16
#        - gateway: 172.20.0.1

volumes:
  cache:
    driver: local
  ssl:
    driver: local